### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by ChamaraDilshan** [cepdnaclk/e18-co227-Interactive-Department-Map-GroupA#9]
- [x] contact the project owner
- [x] planning and research
- [x] create project proposal and presentation
- [x] Practice the presentation 
- [x] Create a sample model
